### PR TITLE
Anders subsampled

### PR DESCRIPTION
**Pull request by davidhassell**
Hi Anders,

It's really good. 

My review is a work in progress, and, as you say, is more a starting point for more discussion.

Happy to have a call later today/tomorrow

More comments to follow later today

Thanks,
David

### CODE REVIEW

**Comment by AndersMS** [comment]
Hi David,

Thank you for the positive feedback.

I am reading your first edits now. I will be here for another couple of hours. Let's see if we do a call today or tomorrow.

Anders

**Comment by davidhassell** [comment]
Sounds good. I'll post some thoughts on the rest soon.

**Comment by erget** [comment]
Hi both, just wanted to drop in and say thanks for the meticulous work - especially with the edits by @davidhassell that CF-ify it a lot I think this is really nice.

**Comment by davidhassell** [comment]
Hi @AndersMS  - I've finished going through it and updated the PR. I think you have done an amazing job at imparting a huge amount of information so succinctly and clearly. As @erget says, I've really only been thinking of CF-ifying it for that different audience, I hope I haven't changed any intent. Do say if I've gone too far, or am not making any sense!

**Comment by AndersMS** [comment]
Hi @davidhassell 

Glad you like it! And thank you for taking the time to review and improve, I really like all the improvements you have introduced! I propose that we set up a zoom call tomorrow, I am about to stop for today.

**Comment by AndersMS** [comment]
Hi @davidhassell 

To answer your question: "Anders: what happens if the tie point coordinates are decreasing in index space - does -0.5 still mean offset to the "left", or is it to the "right" in this case??" 

I am thinking of the offset as being positive in the positive direction of the corresponding dimension, not in the positive direction of the coordinate value. I have recently changed the sign convention for the the offset. As we are now calling it _tie point offset_ I count it negative if the tie point is to the left of its related coordinate point and positive if it is to the right of it, in both cases assuming that the dimension is positive to the right. We can discuss if this is a reasonable convention, it means that the offset typically will be -0.5.

Did that answer the question?
Here is a small illustration:
Picture1

**Comment by davidhassell** [comment]
@AndersMS  - great. A zoom call tomorrow would be good. Any time apart from 14:00-15:00 CET is fine for me.

**Comment by AndersMS** [comment]
Hi @davidhassell 

There are a couple of places where I have square brackets that are not balanced, like here:

"interpolation_dimension: tie_point_index_variable [interpolation_dimension: tie_point_index_variable] …​]"

Should I delete that last square bracket?

**Comment by AndersMS** [comment]
@davidhassell 

Good, zoom call tomorrow.

**Comment by davidhassell** [comment]
@AndersMS I think (checking with the grid_mapping case) it should be `interpolation_dimension: tie_point_index_variable [interpolation_dimension: tie_point_index_variable …​]`

**Comment by davidhassell** [comment]
... so  "to the left" means to the left in index-space, as opposed to physical coordinate space, right? I think I see (after some scribbling of example tie points running in different directions on the back of an envelope) that this always works. This'll needs to be defined somewhere text.

**Comment by AndersMS** [comment]
Yes, that was the way I was thinking.

I agree it should be explained. I would also like to add a small explanation about the differences in tie point indexing for offset and non-offset tie points, so maybe that could be done together, possibly accompanied by an illustration like this:

Picture2

**Comment by davidhassell** [comment]
@AndersMS  - this would be a very useful figure to include.

**Pull request merged**
