### PR TITLE
Make figures numbering relative to the chapter number (in chapter 8).

### PR DESCRIPTION
**Pull request by oceandatalab**

### CODE REVIEW

**Comment by AndersMS** [comment]
@oceandatalab Hi Sylvain, thank you very much. I tried to apply the same principle to chapter 8, but failed. Could you give it a try?  :-)

**Comment by oceandatalab** [comment]
Hi Anders, I already modified the figures numbering in chapter 8 in commit https://github.com/AndersMS/cf-conventions/pull/23/commits/9503bedc3d0e6269e94fc597357fecd29f658916 so I am not sure what you mean.

To make sure I cloned your repository again, switched to the "correct_errors_in_1_9_coordinate_subsambling" branch and compiled the document: I get figures numbered 8.1, 8.2, 8.3 and 8.4 as expected.

Can you please check that you are working on the right branch?

**Comment by AndersMS** [comment]
Sorry, I meant to write:

I tried to apply the same principle to chapter **7**, but failed. Could you give it a try? :-)

There are two figures in chapter 7. Just for consistency within the document.

We could also consider changing Appendix I, but it does already have the chapter dependent figure numbering, but not as elegant as the way you did it :)

**Comment by AndersMS** [comment]
@oceandatalab 
I did successfully merge your Pull Request into my repository - Thank You :-)

**Comment by oceandatalab** [comment]
Ok :)

I created another pull request (https://github.com/AndersMS/cf-conventions/pull/24) for the harmonization of figures numbering in chapter 7 and appendix I

**Comment by AndersMS** [comment]
Excellent, thank you. I have merged the Pull Request into my repository.

**Pull request merged**
